# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(480, 687)
        mainWindow.setStyleSheet("background-color: #1E1E1E;")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 481, 141))
        self.frame.setStyleSheet("background-color: #FFB74D;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.name_gui = QtWidgets.QLabel(self.frame)
        self.name_gui.setGeometry(QtCore.QRect(170, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Oriya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.name_gui.setFont(font)
        self.name_gui.setStyleSheet("color: white;")
        self.name_gui.setObjectName("name_gui")
        self.picture_gui = QtWidgets.QLabel(self.frame)
        self.picture_gui.setGeometry(QtCore.QRect(180, 50, 141, 71))
        self.picture_gui.setText("")
        self.picture_gui.setPixmap(QtGui.QPixmap("../../../../Downloads/to-do_list_1.png"))
        self.picture_gui.setObjectName("picture_gui")
        self.input_line = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line.setGeometry(QtCore.QRect(20, 160, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.input_line.setFont(font)
        self.input_line.setStyleSheet("color: white;\n"
"border: 3px solid #FFA500;\n"
"border-radius: 30;")
        self.input_line.setObjectName("input_line")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(20, 630, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Oriya")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton{\n"
"background-color: #FFA500;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #FF6A00;\n"
"}\n"
"")
        self.btn_save.setObjectName("btn_save")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(320, 630, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Oriya")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("QPushButton{\n"
"background-color: #FFA500;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #FF6A00;\n"
"}\n"
"")
        self.btn_delete.setObjectName("btn_delete")
        self.listbox = QtWidgets.QListWidget(self.centralwidget)
        self.listbox.setGeometry(QtCore.QRect(20, 270, 441, 351))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.listbox.setFont(font)
        self.listbox.setStyleSheet("color: white;\n"
"border: 3px solid #FFA500;\n"
"border-radius: 15;\n"
"")
        self.listbox.setObjectName("listbox")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(90, 230, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Oriya")
        font.setPointSize(18)
        self.label_info.setFont(font)
        self.label_info.setStyleSheet("color: white\n"
"")
        self.label_info.setObjectName("label_info")
        self.btn_complete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_complete.setGeometry(QtCore.QRect(170, 630, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Oriya")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_complete.setFont(font)
        self.btn_complete.setStyleSheet("QPushButton{\n"
"background-color: #FFA500;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #FF6A00;\n"
"}\n"
"")
        self.btn_complete.setObjectName("btn_complete")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.name_gui.setText(_translate("mainWindow", "To-Do-List"))
        self.input_line.setPlaceholderText(_translate("mainWindow", "Введите задачу которую хотите выполнить:"))
        self.btn_save.setText(_translate("mainWindow", "СОХРАНИТЬ"))
        self.btn_delete.setText(_translate("mainWindow", "УДАЛИТЬ"))
        self.label_info.setText(_translate("mainWindow", "Список задач к выполнению:"))
        self.btn_complete.setText(_translate("mainWindow", "ВЫПОЛНЕНО"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
